### PR TITLE
Fixed #4945: fixed the layout of alert message that appears on erasing an entry with lengthy titles

### PR DESCRIPTION
**Pull request by AbrahmAB**
Used Ellipsis for entries with lengthy titles instead of the whole title.

### CODE REVIEW

**Comment by quozl** [comment]
Your solution is not scalable to different font sizes and display widths.

Better to set the GtkLabel property *ellipsize*; search sugar and sugar-toolkit-gtk3 repositories for examples, and refer to the Python GI API reference for GtkLabel.

**Comment by AbrahmAB** [comment]
Setting ellipsize in sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/graphics/style.py would be a better solution. 
Can I send another PR in sugar-toolkit-gtk3 to set the ellipsize in alert.py?

**Comment by AbrahmAB** [comment]
It looks like the bug is in alert.py file that the message and title are not set to ellipsize. 

No need to make changes in sugar repo. Instead I would like to fix the bug in sugar-toolkit-gtk3 .
@quozl Can I close this PR now?

**Comment by quozl** [comment]
Agreed, you will most likely fix the problem in sugar-toolkit-gtk3, so
when you have a new pull request add reference here and close.

**Comment by AbrahmAB** [comment]
Done!
Reference to my pull request in sugar-toolkit-gtk3 [#310](https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/310).

**Pull request closed without merging**
