### PR TITLE
Get audio and video mimes from GStreamer during first start

### PR DESCRIPTION
**Pull request by samdroid-apps**
Replaces #472

### CODE REVIEW

**Comment by quozl** [comment]
Has a bug label, but can't find a bug in trac, what bug number is it?

**Comment by godiard** [comment]
@quozl  http://bugs.sugarlabs.org/ticket/3826

**Comment by quozl** [comment]
Thanks.  Actually looks like a feature that happens to have a bug number.  ;-)

**Comment by samdroid-apps** [comment]
@quozl Your right, this is a feature.

I'm not 100% sure this is a very necessary feature looking back on things.  To be honest, 5sec extra 1st startup time wait seems like a lot to have the right mime type icons - especially when there is no way for activities to use this data.

I think we can close this patch.

**Pull request closed without merging**
