### PR TITLE
Port from GObject to GLib

### PR DESCRIPTION
**Pull request by Pro-Panda**
While I have made the changes discussed in https://github.com/orgs/sugarlabs/projects/5, please mention if I have missed any

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed to 7af77eac.

* [ ] in general, function argument lists that were indented under the first argument are no longer indented,
* [ ] `extensions/cpsection/aboutme/view.py` needs an import,
* [ ] `extensions/cpsection/backup/backends/volume.py` has a `GObject.GError` that can most likely change to `GLib.GError`, and then because no references remain, remove the import of `GObject`,
* [ ] `extensions/cpsection/datetime/view.py` needs an import,
* [ ] `extensions/cpsection/frame/view.py` no longer needs an import of `GObject`, but needs an import of `GLib`,
* [ ] `extensions/cpsection/keyboard/view.py` incorrectly calls `GObject.GObject.__init__` in `LayoutCombo` leaving the `Gtk.HBox` parent class uninitialised, (not your doing, but it is a reference to `GObject`),
* [ ] `extensions/cpsection/language/view.py` no longer needs an import,

... at this point I got bored and figured I could just use flake8 twice and compare,

```bash
git checkout master
python -m flake8 . > flake8-master
git checkout port-gobject-glib
python -m flake8 . > flake8-glib
meld flake8-master flake8-glib
```

Much nicer.  Leave it to you?

(p.s. there are plenty of flake8 issues already, so the compare output method can help instead.)

**Comment by quozl** [comment]
Thanks.  Reviewed 93095ce using flake8 comparison.

```
extensions/cpsection/aboutme/view.py:368:13: F821 undefined name 'GLib'
extensions/cpsection/aboutme/view.py:369:26: F821 undefined name 'GLib'
src/jarabe/main.py:62:1: F401 'GObject' imported but unused
src/jarabe/view/keyhandler.py:20:1: F401 'GObject' imported but unused
src/jarabe/view/keyhandler.py:167:13: F821 undefined name 'GLib'
```

Also several argument list indentation changes, and a few line too long.

**Comment by Pro-Panda** [comment]
Thanks. 
Running `flake8` didn't show these errors for me. Diagnosing.

Fixed the instances and set PEP8

**Comment by quozl** [comment]
Thanks.  a5f87d1 is nearly there, though keyhandler.py still has a GObject import unused (F401).

c0d53eb is more than is needed, and I don't have time to review it, my preference is to omit it, as there's the pending python3 branch to merge with eventually.

As for why flake8 didn't show them for you;
* make sure you are running the python2 version of flake8 (`python2 -m flake8 .`),
* make sure you don't have a .flake8 file higher up in your directory tree or user home directory, and;
* you have an E402 ignore in a .flake8 file at the level of this repository (because otherwise several reports are omitted).

**Comment by Pro-Panda** [comment]
Thanks again.
Please re review

**Pull request merged**
