### PR TITLE
add accelerator for control panel open

### PR DESCRIPTION
**Pull request by quozl**

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Why?

Why alt-shift-m of all keys?  Why is m for controlpanel?

**Comment by quozl** [comment]
Thanks for discussion.

> Why?

Because of [#4660](http://bugs.sugarlabs.org/ticket/4660).  See #497, where this was first proposed, and you closed it to stop discussion.

> Why alt-shift-m of all keys? Why is m for controlpanel?

"[M]y Settings".  Because nobody came up with a better key.

**Comment by quozl** [comment]
Rebased.

**Comment by samdroid-apps** [comment]
That makes a ton of sense now

**Pull request merged**
