### PR TITLE
favoritesview: enable all home view layouts

### PR DESCRIPTION
**Pull request by ortegaps**
This is a GCI task and requires to enable all the home views
that we already have coded.

### CODE REVIEW

**Comment by quozl** [comment]
Tested.

* in square view, corner icons overlap; perhaps the square view code has not been adjusted for a change in icon size, you might compare other changes to the same file since the square view was disabled or added,

Reviewed.

* include reasons why the home views are being enabled, and why they were not enabled already,
* in your commit message don't undermine patch review by mentioning that your work is part of a GCI task; patch review is no different whether the work is part of GCI, a regular volunteer or a paid third-party contractor.

square

**Comment by chimosky** [comment]
@quozl I tested on a wider screen, 3440x1440 and don't notice the icon overlap.
Screenshot from 2022-06-27 01-37-30
 
Could you confirm that the issue still persists?

**Comment by quozl** [comment]
That's great.  My guess is something changed since my original test,
which was at about 1355 x 759 pixels.  An odd resolution.

Sorry, don't currently have time to test again.  If it's working now
with current release of Sugar and dependencies, then close this.

**Comment by chimosky** [comment]
> Sorry, don't currently have time to test again.  If it's working now
with current release of Sugar and dependencies, then close this.

Seeing as the aim of the PR is still valid, I think we should close by merging.

**Comment by chimosky** [comment]
@quozl if you have no objections I'll be merging this.

**Comment by quozl** [comment]
Okay.

**Pull request merged**
