### PR TITLE
Add a dbus method to provide information about a bundle path

### PR DESCRIPTION
**Pull request by godiard**
This is used in the toolkit to provide the get_bundle functionality.

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.

**Comment by tchx84** [comment]
Tested in sugar-build/fedora21.

**Comment by godiard** [comment]
Tested on F22, F18 and ubuntu image.

On Thu, Jul 2, 2015 at 6:46 PM, Martin Abente Lahaye <
notifications@github.com> wrote:

> Tested in sugar-build/fedora21.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sugarlabs/sugar/pull/549#issuecomment-118177668>.
>



-- 
Gonzalo Odiard

**Comment by godiard** [comment]
Merged with tch approval.

**Pull request closed without merging**
