### PR TITLE
Use tick based animation for the desktop and frame

### PR DESCRIPTION
**Pull request by samdroid-apps**
Requires https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/213

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Could we merge this?

**Comment by godiard** [comment]
I think this is a interesting change, but we need test in XO-1 and the other models, and with different gtk versions. I don't see anything wrong in the code, but want do a good test. The changes are small, then (probably) we can merge after freeze.

**Comment by samdroid-apps** [comment]
We have passed the String/UI/API freeze, but would we be able to merge this or do we need to push this back to 0.108?

**Comment by godiard** [comment]
No without testing and performance comparison in all our common hardware (XO-1. XO-1.5, XO-1.75, XO-4). Maybe you can coordinate with Ignacio.

**Comment by samdroid-apps** [comment]
Ok, let's aim to 108 for this patch!

**Comment by quozl** [comment]
Need a test plan, see sugarlabs/sugar-toolkit-gtk3#213 for my comment there.

**Comment by samdroid-apps** [comment]
Feature page:  http://wiki.sugarlabs.org/go/Features/Tick_based_animation

**Comment by quozl** [comment]
Thanks.  Tested on commodity hardware with GTK+ 3.10.  The transitionbox animation was much smoother.  The frame animation was slightly different but was still stepped.  Measuring CPU cycles during test; the frame show operation is CPU bound.  It was surprising how much CPU time was needed for such a straightforward animation, and I wonder if there is some other underlying problem in the existing code.

**Comment by samdroid-apps** [comment]
@quozl Thanks for testing.  I attempted to reproduce the issue with the frame animation using all of the cpu, however it had no noticeable impact on cpu usage (Fedora 23 Rawhide on Core2Duo laptop).

My 2c is that there have probably been some window manager fixes since your release.  For example, I noticed that the grey boxes usually left while the frame is animating had gone away.  But IDK :smile:

**Comment by quozl** [comment]
My test was with Ubuntu 14.04.2 amd64.  Window manager should not be involved, as these windows are undecorated.  The CPU usage was by the shell process.  I used top(1) with 0.1 second update interval.  Yes, it would probably be very fast on a core2duo, wish they were cheap enough to use in a wide deployment.  :grinning:

**Pull request closed without merging**
