### PR TITLE
Add BundleLauncher

### PR DESCRIPTION
**Pull request by samdroid-apps**
By @manuq

FIXME, description to be written

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
Requires https://github.com/manuq/sugar-toolkit-gtk3/compare/start-activity?expand=1

**Comment by SAMdroid-apps** [comment]
Bringing some old points from the discussion:

* It needs to link with the ASLO when the activity is not available.  That is very easy to do with the new ASLO :smile:

**Comment by SAMdroid-apps** [comment]
It has a few things to fix, but it does all the stuff to start using it!  Use cases to implement:

* [ ] Open files in browse, default to show in journal
* [ ] Get Books Activity
* [ ] Please give me ideas!

**Comment by SAMdroid-apps** [comment]
Merged!

**Comment by SAMdroid-apps** [comment]
(Also merged the sugar-toolkit-gtk3 patch)

**Comment by tchx84** [comment]
Hello Sam,

A few comments regarding this. This is clearly a new feature, and as we agreed yesterday during the meeting, there should be a minimum of design discussion on the mailing list, the fact that the patch is old doesn't mean we should not discuss it. It is important to have feedback from the people who previously reviewed this (and that are still around) ie., @godiard.

Other minor details with this PR, are that the description text says "FIXME, description to be written". We also mentioned yesterday that we should put a bit more of love in these formalities. Or the log itself won't make much sense. Both files added here and in toolkit does not pass pep8. And there was no test case for this feature.

We still have time until mid May to get this in properly, so please lets no rush on getting new features in. I have reverted both commits, this and in toolkit-gtk3, please lets do these things properly.

**Comment by godiard** [comment]
@SAMdroid-apps, why hurry up? give us a little of time. also, you are sending the pr, anybody else should merge it. If not, not peer review was done.

**Comment by SAMdroid-apps** [comment]
OK, sorry about that.

It is not my patch, I just clicked the send a pull request button on
Manuq's comparison.

**Comment by godiard** [comment]
manuq didn't sent the pr because was not ready. if you want finish his work (that would be great) we need follow the procedure to have a feature ready , make the review, and then, merge.

**Comment by tchx84** [comment]
It's OK @SAMdroid-apps, your enhtusiasm is welcome :) But lets keep working on it as @godiard said.

**Pull request closed without merging**
