### PR TITLE
Do not set the cursor globally

### PR DESCRIPTION
**Pull request by erilyth**
Issue where the cursor is not being reset even when we exit 'Sugar'.
Discussed on mailing list - '[Sugar-devel] Mouse pointer changes into sugar style pointer in ubuntu'

### CODE REVIEW

**Comment by jvonau** [comment]
Some background https://github.com/sugarlabs/sugar/commit/ea803cb709587d506434e09c37fe9f4dfd2128d8

What if the user's starting 'cursor-theme' was not 'default', this would alter that user's choice of themes. Might want to read the current setting, save it and use the observed value to restore the user's previous setting in place of using 'default'.

**Comment by erilyth** [comment]
@jvonau, It now gets reset to the user's original cursor.

**Comment by jvonau** [comment]
should address inadvertent changing of a user setting, currently untested by myself.

**Comment by quozl** [comment]
Would like also to support running /usr/bin/sugar in GNOME or Unity desktop; the cursor should be private to Sugar and activities, not infect all other desktop apps.

**Comment by erilyth** [comment]
@quozl ,how do you think I should proceed to get that done? I am a little new to this part of Sugar, generally worked more with activities within Sugar.

**Comment by quozl** [comment]
@erilyth, look for a more subtle way to set the cursor.  Changing GSettings is overkill, and dates from the time that Sugar was alone on a device.

**Comment by davelab6** [comment]
I filed an issue on bugs.sugarlabs.org about this but it awaits moderation

**Comment by quozl** [comment]
@davelab6, i'm not even sure who does moderation duties on bugs.sugarlabs.org.

**Comment by davelab6** [comment]
> @davelab6, i'm not even sure who does moderation duties on bugs.sugarlabs.org.

Aha! :) 

@walterbender do you know who does moderate bugs.sugarlabs.org? 

When I submit tickets it says,

> Moderation required for new ticket.
>
> Thank you for submitting a new ticket ("Create sugar-event-recorder-daemon package as required part of sugar desktop").
>
> Your submission has been routed to Samuel Cantero for approval. We make every effort to review submissions within one working day.
>
> If you provided a valid e-mail address with your submission, you will receive e-mail notification if the moderator accepts your submission.

**Comment by quozl** [comment]
Ah, okay, thanks.  Not being subject to moderation means I'm ignorant.  Samuel Cantero is regularly responsive on systems@ mailing list.

**Comment by davelab6** [comment]
Okay cool, I'll post there and CC him as I found his email :)

**Comment by erilyth** [comment]
@quozl There are ways to set the cursor using Gdk, but the problem is that the cursor needs to be set individually for every activity. Since the cursor is set on a given window. Would this be okay or should I look for something better?

**Comment by quozl** [comment]
@erilyth, that's great, sounds like what we need.  So you'll be able to put that in sugar-toolkit-gtk3 in the activity common code.  Once you show us that, I can look at whether I can backport it to sugar-toolkit (gtk2).

**Comment by erilyth** [comment]
@quozl , I'll send a PR to sugar-toolkit-gtk3

**Pull request closed without merging**
