### PR TITLE
Erasing and Erased alert for 'Erase' option in List View

### PR DESCRIPTION
**Pull request by i5o**
This add an Erasing alert while the activity is being erased
also adds a "Erased" notifyalert for when the erase process is done.

The idea is to give feedback to user, not just to update the listview.

### CODE REVIEW

**Comment by samdroid-apps** [comment]
What is the rational behind this patch?

Removing an activity is very fast, so the user is probably still going to be at the list view when the activity is removed.

Since it is so fast, do we really need an alert to say it is doing something?

**Comment by i5o** [comment]
Maybe it could be useful with old hardware.
I tested with SimpleWikipedia activity and it tooks few seconds (XO-4)

I will test on XO-1 and reply

2015-10-09 19:16 GMT-02:00, Sam <notifications@github.com>:
> What is the rational behind this patch?
>
> Removing an activity is very fast, so the user is probably still going to be
> at the list view when the activity is removed.
>
> Since it is so fast, do we really need an alert to say it is doing
> something?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sugarlabs/sugar/pull/581#issuecomment-146987930


-- 
Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>

**Comment by i5o** [comment]
it tooks few more seconds on XO-1, I tried to remove Measure activity and Scratch..

Maybe I should test with Wikipedia..
So maybe instead of "Erasing" alert, we just could set the cursor to watch while erasing, and turn it to normal after it

**Comment by samdroid-apps** [comment]
Yeah, sounds good

**Comment by i5o** [comment]
Doing it

**Pull request closed without merging**
