### PR TITLE
Brightness controls try9

### PR DESCRIPTION
**Pull request by tchx84**
This PR is for adding brightness control capabilities to Sugar. It includes a generic mechanism to interact with backlight devices, a jarabe model that acts as an abstraction for the sugar shell, keyboard control keys and a device frame UI.

### CODE REVIEW

**Comment by tchx84** [comment]
This PR replaces https://github.com/sugarlabs/sugar/pull/510, making Brightness model constant _private.

**Comment by tchx84** [comment]
Github meeses with the commits order, to see the original order please take a look at https://github.com/tchx84/sugar/commits/brightness-controls-try9

**Comment by tchx84** [comment]
This also needs https://github.com/sugarlabs/sugar-artwork/pull/51

**Comment by samdroid-apps** [comment]
Since this patch adds an almost required polkit policy, could we add that to the makefile or the docs or something?

**Pull request merged**
