### PR TITLE
Add links to 'Sugar logging in' tutorial

### LINKED ISSUE #892: Explain log in with the Sugar desktop selected
"log in with the Sugar desktop selected" is not easy to decode for people who don't know how to use the features of the greeter program, and the desktop selection list.  This is made harder because gdm3 does not clearly explain the feature on screen, instead showing a gear logo.

* [x] refer to gdm3 documentation,
* [ ] add script-annotated screenshots of gdm3,
* [ ] maintain for each release of Fedora and Ubuntu,

### PR DESCRIPTION
**Pull request by shaansubbaiah**
Add links to Sugar login tutorial available at [sugar-docs](https://github.com/sugarlabs/sugar-docs/blob/master/src/sugar-logging-in.md) 

Fixes #892

### CODE REVIEW

**Comment by shaansubbaiah** [comment]
The first commit appears to be due to merging changes to my fork from upstream. To remove it, I can delete the current fork, create another fork, then add these changes (or) Can only the last 2 commits be merged and pushed?

**Comment by chimosky** [comment]
Reviewed, thanks. 

The two commits can be cherry-picked but you can also do an interactive rebase to the current master and drop the merge commit.

```
$ git rebase -i f1ac684
*change `pick` to `drop` and continue rebase.

**Comment by shaansubbaiah** [comment]
I tried the above snippet you sent and tried to rebase it, didn't have that commit as an option. Installed GitKraken and was also unsuccessful. Shall I create another branch and make a new PR?

**Comment by srevinsaju** [comment]
@shaansubbaiah 

```
git rebase -i f1ac68488631ab153dd31b737819fd5cadc3b158
```
then, if you do not see https://github.com/sugarlabs/sugar/pull/918/commits/c60e316e693c20b4996c15cbcbba66f3cdeecd8f

Then just save and close to complete the rebase

```bash
git push -f 
```
It should fix it in theory

**Comment by chimosky** [comment]
Squashed and merged by hand.

**Comment by shaansubbaiah** [comment]
@chimosky Thanks, I tried what @srevinsaju suggested and it didn't work. I must have messed up my git tree pretty badly somehow. 

I'll go through more git tutorials so it doesn't happen again 👍

**Pull request closed without merging**
