### PR TITLE
Don't ask for gender on default

### PR DESCRIPTION
**Pull request by kipply**
This will disable asking for gender on startup. Selecting gender will still be available in the About Me section of the settings, however it won't be required. I also set the default age selection icons used (when a gender isn't set) to use the 'male' icons since the clothing there is more generic. 

Fixs #770

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  Please look at the `default-nick` value handling.  Requesting changes;

- [ ] move the new GSettings key from `org.sugarlabs` to `org.sugarlabs.user`,
- [ ] rename the new GSettings key from `gender-onstart` to `default-gender`, to fit with the naming and use of existing `default-nick`, with default value _disabled_ (which will skip the gender page), and possible other values _male_, _female_, and empty string, (which will show the gender page with the default),
- [ ] split your one patch into at least three; the schema trailing whitespace changes, the default age selection icons, and the not asking for gender on startup; it will simplify future `git bisect`,
- [ ] your `_IntroBox` class changes are difficult to read; it seems a complicated way to suppress a page, and it may be better to have `back` and `next` iterate through a list of pages now instead of use page numbers; this class is very old (2008) and did not anticipate optional pages.

I did not yet test your code, but I did test logout and login after clearing `nick`;
```
gsettings set org.sugarlabs.user nick ''
```
So that will be my test case, combined with other GSettings values.

**Comment by kipply** [comment]
Thanks for the review! My branch has been amended with the requests.

**Comment by quozl** [comment]
Thanks.  Nearly there.

Tested 07ac0e1.  Fails if the GSettings schema is not updated.

```
(main.py:2759): GLib-GIO-ERROR **: Settings schema 'org.sugarlabs.user' does not contain a key named 'default-gender'
```

- [ ] please place the `default-gender` settings read inside an exception handler; because we sometimes have people use parts of commits and not others,

Does not show a default gender if `default-gender` is set to `female`.  Didn't test `male`.

- [ ] when `default-gender` is set to `male` or `female`, show that as the default in the gender intro page.

- [ ] expand the schema description for the key; it does not describe the values that can be used,

Merged two of three patches as correct and uncontentious, you may wish to rebase.

**Comment by kipply** [comment]
Updated! I'd avoid a bare except, but it doesn't actually seem to throw an exception?

**Comment by quozl** [comment]
You're right.  Sorry, I was wrong.  We don't have much code that handles missing GSettings schema update.  What we do have uses `Gio.Settings.list_keys()` instead of an exception handler.

I've changed my mind; feel free to not handle a missing schema update.

**Comment by kipply** [comment]
No problem :) 

Updated, and it includes a check to see if `default-gender` is in the keys.

**Comment by quozl** [comment]
Thanks, great work.  Reviewed and tested.

**Pull request merged**
