### PR TITLE
fix for #2974

### PR DESCRIPTION
**Pull request by quozl**
Fix for spurious "failed to start" message, solved while testing repeated Write-96 resume from journal on Fedora 18.

http://bugs.sugarlabs.org/ticket/2974

### CODE REVIEW

**Comment by godiard** [comment]
Thanks for working on this issue.
I think we should include it. 
Can you fix this simple pep8 error, and send  a new pr?
```
pep8 src/jarabe/model/shell.py
src/jarabe/model/shell.py:742:37: E128 continuation line under-indented for visual indent
```

**Comment by tchx84** [comment]
+1, new PR with pep8 fixes and goes in :)

**Comment by quozl** [comment]
Okay, thanks, expect to do that within four weeks.

**Comment by godiard** [comment]
@quozl, I can that for you if you are busy. Just don't want steal the credit.

**Comment by quozl** [comment]
Well, since the PEP8 detection was you, and not me, you wouldn't be stealing any credit.  ;-)  If I was a maintainer, I'd merge the patch and immediately commit a PEP8 patch referring to the PEP8 regression introduced in the previous patch ...

**Comment by godiard** [comment]
Ok. Pushed and added another patch with the pep8 fix

**Pull request closed without merging**
