### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FGrose**
Fix typos and avoid a numbers controversy.
Provide some web links (for the GitHub front page).

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.  I suggest making both links look similar in style, the way you have them at the moment one has https prefix the other does not.

**Comment by samdroid-apps** [comment]
Closing.  We need the links in the same style please.  Actually maybe we could even have text labels instead of urls.

**Comment by quozl** [comment]
@FGrose, in case it isn't obvious, this project has a policy of never re-working submitted changes that fail review, but rather it gives the opportunity to the original contributor to work with feedback and submit again.  If you've no time to do that, say so, and one of us will take over.  Until then we may consider the area of change off-limits because you've expressed interest.  Thanks for your contribution.

**Comment by FGrose** [comment]
ok, good to know.  See https://github.com/sugarlabs/sugar/pull/591.
I'm happy if a maintainer wants to amend the commit.

**Pull request closed without merging**
