### PR TITLE
Fix bundle install issues

### PR DESCRIPTION
**Pull request by tchx84**
THIS IS JUST A DRAFT PLEASE READ AND NOT MERGE: READ COMMIT LOGS

### CODE REVIEW

**Comment by tchx84** [comment]
@quozl @samdroid-apps @i5o @godiard if you agree I can re-submit for merging...

**Comment by samdroid-apps** [comment]
@tchx84 this looks great.  I haven't tested just reviewed.  I will test.

**Comment by samdroid-apps** [comment]
Tested, works great

**Comment by samdroid-apps** [comment]
Please resubmit or merging

**Comment by tchx84** [comment]
alright!

**Pull request closed without merging**
