### PR TITLE
Add weblate sync workflow

### PR DESCRIPTION
**Pull request by chimosky**
This will automatically open a PR whenever weblate pushes changes to weblate-sync.

### CODE REVIEW

**Comment by quozl** [comment]
File name has syc; does it need it?

**Comment by chimosky** [comment]
Thought I'd fixed it earlier, thanks for pointing it out.

**Comment by chimosky** [comment]
@quozl you're find with merging this right?

**Comment by quozl** [comment]
I've no real objection.  I don't like the idea of more notifications, when the step involved doesn't need to happen until release it could just as easily be part of release process, and for the previous releases that's how I handled it.

**Comment by chimosky** [comment]
Seeing as this removes the need to manually do it at release, I think it's a good thing.

**Pull request merged**
