### PR TITLE
Hide battery icon when battery is not present

### PR DESCRIPTION
**Pull request by i5o**
Right now it shows a full white battery when it's not present
more logical would be if its not showed.

This patch does that

### CODE REVIEW

**Comment by samdroid-apps** [comment]
I will test this

**Comment by samdroid-apps** [comment]
Doesn't cause any issues when the battery is not removed.

Lemme test what happens when you remove the battery

**Comment by samdroid-apps** [comment]
Will not merge.  It doesn't work.

If I take out my battery while sugar is running, it doesn't take the battery out of the frame.

**Comment by i5o** [comment]
Are you using it on a Xo or Sugar-Build?

It works for me in a XO

**Comment by samdroid-apps** [comment]
Further testing showed that the battery removal code does not work on sugar-build before or after this patch.  That's funny, because it seems to have access to the battery fine (it shows the %)

**Comment by samdroid-apps** [comment]
Works really nicely on XO4.  It even animates when you remove that battery!

Please refrain from adding "This patch does that" to the end of your commit message for next time.  I should have seen that before I merged the patch, but whatever.

**Pull request merged**
