### PR TITLE
Social Help

### PR DESCRIPTION
**Pull request by samdroid-apps**
WebKit2 is the new version of GtkWebKit that has all the cool new stuff.  It
has a slightly different api, but it is basically the same.

Migrating to WebKit2 is needed because there can only be 1 version of WebKit
per process, meaning if the help view uses the old version everything else
is forced to as well.

### CODE REVIEW

**Comment by tchx84** [comment]
@SAMdroid-apps @godiard just to note: plugins in the WebServices CP section also use webkit.

**Comment by godiard** [comment]
@tchx84, Thanks by the remainder, but I can't find code for the webservices already included in Sugar using webkit.
{{{
[gonzalo@localhost sugar]$ grep -ri webkit --include=*.py
src/jarabe/view/viewhelp.py:from gi.repository import WebKit
src/jarabe/view/viewhelp.py:        webview = WebKit.WebView()
}}}
Is a separated discussion, but probably we should include the working webservices in Sugar. If not configured they do nothing, and I am afraid today they are difficult to find and install for mot of the users.

**Comment by godiard** [comment]
Wrong markup
```
[gonzalo@localhost sugar]$ grep -ri webkit --include=*.py
src/jarabe/view/viewhelp.py:from gi.repository import WebKit
src/jarabe/view/viewhelp.py: webview = WebKit.WebView()
```

**Comment by SAMdroid-apps** [comment]
> 1) You said: "Migrating to WebKit2 is needed because there can only be 1 version of WebKit
per process, meaning if the help view uses the old version everything else
is forced to as well." This is the only instance of WebKit running in the sugar process I think. What is the other?

I was planning to use WebKit2 for socialhelp.  I know that help doesn't need shiny new web standards, but discourse (the forum) has all the shiny new browser stuff.

**Comment by SAMdroid-apps** [comment]
>  2) I know we use __app_scheme_cb in the web activities, but,is this something required by the change to WebKit2, a recommendation or is something optional?

The alternatives seem to have disappeared.

**Comment by SAMdroid-apps** [comment]
> @SAMdroid-apps @godiard just to note: plugins in the WebServices CP section also use webkit.

Hum, I tested that, and things aren't looking good.  The  webservices try to import another version of webkit which crashes the whole thing :(

It is pretty easy to migrate individual web services.  But the issue is that we have to migrate everything at the same time!

**Comment by godiard** [comment]
@SAMdroid-apps, @tchx84, the only way is have these services included in Sugar. Could be a task for 0.106?

**Comment by SAMdroid-apps** [comment]
@godiard, sorry I don't get what your trying to say?

**Comment by SAMdroid-apps** [comment]
I just pushed the social help popup:

**Comment by SAMdroid-apps** [comment]
Ok, I just pushed the 3 social help commits.  It is done feature wise.

```
commit bd8360d8c62c469f6d96c3cc55bf435716794d81
Author: Sam Parkinson <sam.parkinson3@gmail.com>
Date:   Sun Apr 12 16:33:54 2015 +1000

    Let users change social help server in the settings
    
    Hat tip to @prasoon2211 who created the commit that this one is based on.

commit 496cf8a6c0c091d09eb22fca6903b49c844588d5
Author: Sam Parkinson <sam.parkinson3@gmail.com>
Date:   Sun Apr 12 08:08:40 2015 +1000

    Add keyboard shortcut for social help

commit 5ea315c465c9eabb534d169eb01de97521520436
Author: Sam Parkinson <sam.parkinson3@gmail.com>
Date:   Sun Apr 12 06:52:38 2015 +1000

    Add a basic social help popup
```

**Comment by SAMdroid-apps** [comment]
Here is a feature page for this patch:  http://wiki.sugarlabs.org/go/Features/Social_Help

**Comment by SAMdroid-apps** [comment]
Please see the video for this feature:  https://www.youtube.com/watch?v=_WzwVZ60Tbw

**Comment by quozl** [comment]
Changes reviewed.  Did not test.

**Comment by samdroid-apps** [comment]
Replaces by #493

**Pull request closed without merging**
