### PR TITLE
Add new translations from Pootle server

### PR DESCRIPTION
**Pull request by leonardcj**

### CODE REVIEW

**Comment by leonardcj** [comment]
@quozl is this the method I should be using (e.g. branch: translations).

**Comment by quozl** [comment]
Yes, that's great, thanks.

**Comment by leonardcj** [comment]
@quozl, ok, I will endeavor to do better in future.  Thanks for pointing out the proper procedure.  BTW, a close look at the LINGUAS change would be appreciated, it can be tricky.

**Comment by quozl** [comment]
034a058 tested against build to .deb, no errors.

0396c75 causes build failure;

{{{
make[2]: *** No rule to make target 'ach.po', needed by 'distdir'.  Stop.
}}}

because there is no `ach.po` file.  Perhaps not added and committed?  There might be others not added.

**Comment by quozl** [comment]
A quick shell hack

```
for x in $(<po/LINGUAS); do [ ! -e po/$x.po ] && echo $x; done | tr '\n' ' '
```

gives me these missing languages

``` ach adh an ast cgg eo et fa_AF fo fur fy ga gd gom gom@latin gun hch ka kk kw lb ln lo mai mfe mh miq mnk mt my nap niu nqo nso oc pms rm sco so su tg ti tk tl tt ve ```

**Comment by leonardcj** [comment]
66b7d6a should contain the missing files. Not sure why they didn't copy over the first time.

**Comment by quozl** [comment]
Only `fa_AF` missing now; either add the file or remove it from LINGUAS?

**Comment by leonardcj** [comment]
Unfortunately Dari (fa_AF) was migrated poorly from the prior Pootle instance and I have not unwound it's conflation with Afrikaans on the Pootle backend, so for now, deleting fa_AF is the best solution.

**Comment by quozl** [comment]
No worries.  Build to .deb worked fine, so I'll squash and merge.

**Comment by leonardcj** [comment]
Made corresponding LINGUAS change (delete Dari fa_AF) in sugar-toolkit-gtk3 repo

**Comment by quozl** [comment]
Thanks.  Just to remind you; your next steps in your `sugar` repository will be to 

* [update your master branch](https://developer.sugarlabs.org/contributing.md.html#keep%20your%20fork%20up%20to%20date) to acquire my squash commit of your four commits,
```
git checkout master
git pull upstream
```
* delete your branch now that it is merged,
```
git branch -d translations
```
* should the delete whinge that you haven't had the work merged, change from `-d` to `-D` and let me know, 'cause I'm interested,

and next time translations are to arrive, update your master branch again and then make a new translations branch;
```
git checkout master
git pull upstream
git checkout -b translations
```

Variations on these commands are quite possible.

**Pull request merged**
