### PR TITLE
Add zoom guesture for desktop views

### PR DESCRIPTION
**Pull request by samdroid-apps**
Centeral the the nvaigation in Sugar is the zoom metaphor.  This
metaphor does not extend to the zoom guesture on multi touch
devices.

This commit adds a zoom guesture controller to the homewindow.
The user can then use the pinch to zoom guesture to switch between
the home, group and mesh views.

This was tested on commodity hardware using fc24 rawhide.

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Does nothing on an xo4 running olpc os 14.

**Comment by quozl** [comment]
> Does nothing on an xo4 running olpc os 14.

What is olpc os 14?

**Comment by samdroid-apps** [comment]
The fc20 build.  Is that 14?

**Comment by quozl** [comment]
Oh, right, you mean 14.1.0, not yet released, and has blocker bugs that haven't had progress for many months.  I was afraid you might have been referring to a deployment build or the Sugar Labs testing build 41002SL.

**Comment by i5o** [comment]
"ping" for the PR, are we going to push this?

**Comment by quozl** [comment]
I'm still puzzled as to why it does nothing on an OLPC XO-4 running 14.1.0, according to Sam.  I've not tested it.  Does it work on an OLPC XO-4 running 13.2.6?  That's probably the most stable touchscreen platform Sugar is run on at the moment.  Hard to test if it doesn't work.

**Comment by samdroid-apps** [comment]
I don't currently have access to an XO4 with 13.2.6.  You are welcome to
test.

**Pull request closed without merging**
