### PR TITLE
Update debian.md

### PR DESCRIPTION
**Pull request by JuiP**
* https://alioth.debian.org/projects/pkg-sugar/ is no longer available. The alioth.debian.org service is discontinued. Its replacement is a GitLab instance at salsa.debian.org.
* `pkg-sugar-commit` mailing list is not found

__TODO__
- [x] find the equivalent of `pkg-sugar git repositories` as the given address redirects to a webpage displaying error 404 not found.

Please verify @quozl

### CODE REVIEW

**Comment by quozl** [comment]
Happy to help.

Method;
* visit packages.debian.org/sucrose,
* click on the latest package,
* click on the source package,
* click on Debian Source Repository,

For example;

https://packages.debian.org/sucrose
https://packages.debian.org/sid/sucrose
https://packages.debian.org/source/sid/sugar
https://salsa.debian.org/pkg-sugar-team/sugar

https://packages.debian.org/python3-sugar3
https://packages.debian.org/sid/python3-sugar3
https://packages.debian.org/source/sid/sugar-toolkit-gtk3
https://salsa.debian.org/pkg-sugar-team/sugar-toolkit-gtk3

There is probably some command line magic tool to achieve something similar without all the clicks.  For example "apt source python3-sugar3" downloads the source and warns that you could have used git, giving the git repository to use.

Best people to engage with on that would be the Debian developer community, not Sugar Labs.

**Comment by JuiP** [comment]
Also how about adding sugars docs for 

- documentation for adding new translations and refreshing the pot files
- Documentation on Port to Collabwrapper - important for activity that uses ExportedGObject.

@chimosky @quozl ?

**Comment by chimosky** [comment]
> Also how about adding sugars docs for
> 
>     * documentation for adding new translations and refreshing the pot files
> 
>     * Documentation on Port to Collabwrapper - important for activity that uses ExportedGObject.
> 
>     * Port from GObject to GLib
> 
> 
> @chimosky @quozl ?

Documentation for translations can be found at the [Translation Team](https://wiki.sugarlabs.org/go/Translation_Team) page on the wiki.

Not all activities use `CollabWrapper` and there's Documentation for using it but you'll have to read the source code and test activity to find out, you can write up something if you have the time.
Also you can take a look at https://github.com/sugarlabs/collabwrapper/issues/10, I haven't been able to get around to looking at the issue but I plan to.

I don't think a documentation for porting from `GObject` to `GLib` is necessary, the [projects](https://github.com/orgs/sugarlabs/projects) page explains what needs to be done.

**Comment by quozl** [comment]
@JuiP, so sorry, I got distracted and edited your comment with my answer instead of making a new comment.

**Comment by Saumya-Mishra9129** [comment]
@JuiP 
- Port from GObject to GLib is documented in our project list and almost completed as by https://github.com/orgs/sugarlabs/projects/5.
- Documentation on Port to Collabwrapper - important for activity that uses ExportedGObject. is already given in http://people.sugarlabs.org/sam/docs-collab-wrapper-try2/sugar3.presence.wrapper.html.
So there is no need for extra documentation according to me. Thanks

**Comment by JuiP** [comment]
Sorry for the late reply and a long comment.
> I'm not sure if you mean sugar-docs or sugar:docs/.

I meant the documentation for maintainers.
> We may lack documentation for uploading the refreshed POT files to translate.sugarlabs.org; I've not seen an uploaded POT file for some years. We may have lost a volunteer, and so reverse engineering the process may be required.

By documentation for adding new translations, I meant refreshing the pot file. I didnot seem to find the documentation initially when I began. @quozl I have even asked about the way in which translations could be added on sugar-devel mailing list as it was confusing initially.

>Documentation on Port to Collabwrapper - important for activity that uses ExportedGObject. is already given in http://people.sugarlabs.org/sam/docs-collab-wrapper-try2/sugar3.presence.wrapper.html.
So there is no need for extra documentation according to me. Thanks

Thanks @Saumya-Mishra9129 . A part of the documentation from [sugar3.presence.wrapper](http://people.sugarlabs.org/sam/docs-collab-wrapper-try2/sugar3.presence.wrapper.html.) has been added to collabwrapper as docstrings.
> Should be already in, or added to CollabWrapper, as it isn't part of Sugar or the Toolkit.
 
Will look up sugarlabs/collabwrapper#10 as suggested by @chimosky 
> I don't think a documentation for porting from GObject to GLib is necessary, the projects page explains what needs to be done.

I agree, how about adding a link to the projects page in [contributing.md](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md)?

**Comment by JuiP** [comment]
I seemed to have digressed from the aim of this PR. Thanks @quozl I have updated the links related to Sugar Packaging on Debian in the commit `17175e2`. Each link now redirects to a valid webpage.
Kindly review and merge.
> There is probably some command line magic tool to achieve something similar without all the clicks. For example "apt source python3-sugar3" downloads the source and warns that you could have used git, giving the git repository to use.

Should I mention anything related to `apt source python3-sugar3` in this doc or leave it to the contributors to figure out?

**Comment by quozl** [comment]
@JuiP,
> I agree, how about adding a link to the projects page in contributing.md?

Sure, if you like.  `git grep` shows we have one in `sugar-docs:src/how-can-i-help.md`, which is a  rephrasing and abbreviation of `src/contributing.md`.

> Should I mention anything related to apt source python3-sugar3 in this doc or leave it to the contributors to figure out?

I don't mind, but I don't see much need.  For things we do not maintain, our role is primarily to point to documentation.  Same reason we don't explain how to use Python or JavaScript features.  We do not maintain `apt` or Debian, so adding documentation for it is (a) redundant, and (b) increases our future maintenance needs.  `sugar:docs/debian.md` in this repository is mostly for users of Debian to install Sugar, or users of Sugar to choose Debian.

In the context of the GSoC project idea _Debian advocacy for Sugar_, most of the work requires skills and techniques that are part of the Debian Project, not part of Sugar.  A focus on documenting the Debian Project at Sugar Labs is misdirected; if some Debian Project documentation needs improving, then it should be improved over there, not duplicated here.

**Comment by JuiP** [comment]
> I don't mind, but I don't see much need. In the context of the GSoC project idea Debian advocacy for Sugar, most of the work requires skills and techniques that are part of the Debian Project, not part of Sugar. A focus on documenting the Debian Project at Sugar Labs is misdirected; if some Debian Project documentation needs improving, then it should be improved over there, not duplicated here.

Thanks for the clarification! 

> Sure, if you like. git grep shows we have one in sugar-docs:src/how-can-i-help.md, which is a rephrasing and abbreviation of src/contributing.md.

Will do that then! :)

**Pull request merged**
