### PR TITLE
Restore GNOME cursor theme on sugar DE exit

### LINKED ISSUE #827: Restore org.gnome.desktop.interface cursor-theme
The Sugar cursor affects the GNOME desktop environment.

This is caused by https://github.com/sugarlabs/sugar/blob/master/src/jarabe/main.py#L205 where the GNOME desktop cursor theme is changed to the Sugar theme.

Workaround is to use `gsettings` to change _cursor-theme_ in _org.gnome.desktop.interface_ back to what it was.  Or you can use `dconf` to reset all settings, but that has many side-effects.

* [ ] read the value of _cursor-theme_ before changing it in the `_start_window_manager` function,
* [ ] keep the _Gio.Settings_ instance instead of deleting at end of the `_start_window_manager` function,
* [ ] restore the old value in the `_stop_window_manager function`.

This should fix the problem for future users.

### LINKED ISSUE #872: Cursor changed automatically
Issue: When I installed sugar desktop environment, the cursor automatically changed on ubuntu even though I did not do it explicitly
The cursor is same as that of sugar DE.

WhatsApp Image 2019-09-04 at 9 10 28 AM

### PR DESCRIPTION
**Pull request by srevinsaju**
Fixes #872 & Fixes #827 
@walterbender @quozl  Please review

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

* [ ] store the old value in memory, not in a file; there's no need to store it in a file,
* [ ] don't instantiate the same Gio.Settings so many times, cache it instead.

**Comment by srevinsaju** [comment]
@quozl  Fixed it,. Please review

**Comment by quozl** [comment]
Thanks.  Reviewed.

* [ ] new global variable _settings_  is specific to one settings, yet others are used in the source, see all references to _Gio.Settings_, this can be confusing,
* [ ] why a dictionary for the cursor?  isn't a single object enough?
* [ ] what is _e_ in the warning, and why is a warning shown?
* [ ] the number of lines added seems excessive.

**Comment by srevinsaju** [comment]
@quozl 

> * [ ]  new global variable _settings_  is specific to one settings, yet others are used in the source, 

see all references to _Gio.Settings_, this can be confusing,
Ok, I had to declare `Gio.Settings` for mouse cursor on `stop_window_manager`. 

> * [ ]  why a dictionary for the cursor?  isn't a single object enough?

I expected to extend the cursors to other DE's which uses GTK or other forks of GNOME like CInnamon, Budgie which  doesn't inherit from Gio.settings-customtheme but uses some other methodology. I don't use CInnamon or Budgie, so well, can't test it.

> * [ ]  what is _e_ in the warning, and why is a warning shown?

Removed it. Used to instantiate user with message, custom cursor theme could not be received from Gio

> * [ ]  the number of lines added seems excessive.

Thats because I created two new functions to handle the events. As mentioned above, I thought it would be useful to extend the existing functions.

**Comment by srevinsaju** [comment]
@quozl made changes on the basis of `IRC` messages: https://github.com/sugarlabs/sugar/pull/897/commits/a358d333f434348d0d6a0235bf16c92b079af2f2

**Comment by quozl** [comment]
Thanks.  New flake8 warnings added;

```log
src/jarabe/main.py:199:1: E302 expected 2 blank lines, found 1
src/jarabe/main.py:202:1: E112 expected an indented block
src/jarabe/main.py:202:3: E999 IndentationError: expected an indented block
src/jarabe/main.py:206:1: W293 blank line contains whitespace
```

* [ ] prefix the global variable with `_` like the others, sorry didn't notice that before,
* [ ] put the global declaration after the function declaration,
* [ ] don't really need those comments,
* [ ] still not sure what the point is of testing the variable; it should never be None, (if the GNOME schema is missing, Sugar won't start),

**Comment by srevinsaju** [comment]
> * [x]  prefix the global variable with `_` like the others, sorry didn't notice that before,
> * [x]  put the global declaration after the function declaration,
> * [x]  don't really need those comments,
> * [ ]  still not sure what the point is of testing the variable; it should never be None, (if the GNOME schema is missing, Sugar won't start),
Yes, in the unlikely case of getting an empty string, it would be incorrect to assign the custom_cursor_theme as 'None', if it ever happens. It would be better to terminate sugar with sugar-cursor unchanged.

**Comment by quozl** [comment]
> Yes, in the unlikely case of getting an empty string, it would be incorrect to assign the custom_cursor_theme as 'None', if it ever happens. It would be better to terminate sugar with sugar-cursor unchanged.

An empty string is fine.  If we get an empty string on entry, we should set an empty string on exit, not _default_.

**Comment by srevinsaju** [comment]
@quozl, thanks for that info. fixed it on https://github.com/sugarlabs/sugar/pull/897/commits/6be7c69e8754be0b878411e56cfeddfe1a29e2a0

**Comment by quozl** [comment]
Thanks.  Reviewed.  Commits added to keep style and minimise change.

**Comment by quozl** [comment]
Probably the last remaining thing;

* [ ] per the issue, and my first review, _keep the Gio.Settings instance instead of deleting at end of the _start_window_manager function_, this is so that time is not wasted setting up and tearing down the Gio.Settings instance; faster logout or shutdown, important if the shutdown is being driven by depleted battery.

**Comment by srevinsaju** [comment]
@quozl have fixed the final correction on https://github.com/sugarlabs/sugar/pull/897/commits/0b89bb2577c84001b5a029447ea6650b91440cd7 .

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested on Ubuntu 19.04 with Sugar 0.116.

**Comment by srevinsaju** [comment]
Thanks @quozl for merging it. I was away for a while :)

**Pull request merged**
