### PR TITLE
Readme.md updated to add links to dependencies.

### PR DESCRIPTION
**Pull request by srevinsaju**
Unwanted Dependencies was mentioned. Most of it automatically installed. Links to dependencies was added;

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@srevinsaju `sugar-datastore` is not installed automatically if you build through the native method(manual installation) on the other hand all the dependencies are automatically installed if you install through the `sucrose` pacakge.

Thanks for the linking part. Please also do it for datastore.

**Comment by srevinsaju** [comment]
@Aniket21mathur updated, but I have not been able to use the sugar DE yet. It stops working at 
```
make: *** No targets specified and no makefile found. Stop.
make: *** No rule to make target 'install'. Stop.

```

**Comment by Aniket21mathur** [comment]
Please follow [this](https://github.com/sugarlabs/sugar/blob/master/docs/development-environment.md#native-sugar) method and let us know where you get stuck. Thanks

**Comment by srevinsaju** [comment]
> Autogen, configure, make, and install modules for Python 3;
 ```
for module in sugar{-artwork,-toolkit-gtk3,-datastore,}; do
    cd $module
    ./autogen.sh --with-python3
    make
    sudo make install
    cd ..
done
```
Here, also see #890

**Pull request merged**
