### PR TITLE
Control panel section keyboard activation

### PR DESCRIPTION
**Pull request by quozl**
Adds keyboard navigation to control panel.

We maintain a list of selected options from search results, detect the return key and if unambiguous result, open section view.

Does not autocomplete like home view search.

### CODE REVIEW

**Comment by samdroid-apps** [comment]
> Does not autocomplete like home view search.

Any reason why¿  consistency is nice.

**Comment by quozl** [comment]
I could make some reasons up.  Any reason why?  Perhaps you could do that part and make a pull request with both features?

**Comment by samdroid-apps** [comment]
Na, this is fine.  I think that the list of cpanels is always visible, so your searching on that whereas in the home view you are searching on an invisible list.

**Comment by samdroid-apps** [comment]
No, sorry, I mis-interpreted the patch.  Testing, say I type `back`, and press enter.  Nothing happens :(  I'll hack soomething on top of that.

**Comment by samdroid-apps** [comment]
My apologies, that was a bad test.  There is both background and data.  Evidently the disabled styles are broken again.

**Comment by quozl** [comment]
Thanks.  I didn't see that effect on Fedora 18.  :grin:

**Pull request merged**
