### PR TITLE
Comma missing fix

### PR DESCRIPTION
**Pull request by ujdhesa**

### CODE REVIEW

**Comment by walterbender** [comment]
This looks good. @samdroid-apps are we OK with merging string changes at the moment?

**Comment by i5o** [comment]
@samdroid-apps Is this mergeable for 0.112? Or whatever the next version is?
+ https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/341
+ https://github.com/sugarlabs/sugar/pull/726

**Comment by quozl** [comment]
We've passed 0.110.0 and so the string freeze should be over, per the Wiki.  Previous stable updates have used a branch, such as 0.108.1.

 * http://wiki.sugarlabs.org/go/0.108/Roadmap
 * http://wiki.sugarlabs.org/go/0.110/Roadmap

**Comment by i5o** [comment]
I see. I'll let @samdroid-apps or anyone else to merge this. Even @quozl if you want.

I have no idea on how string works :P

**Comment by quozl** [comment]
> Even @quozl if you want.

I'm not someone who merges here, sorry.  :smile:

**Comment by godiard** [comment]
@quozl, sent you a invitation.

**Pull request merged**
