### PR TITLE
Display an alert after duplicating bundles in view source 

### PR DESCRIPTION
**Pull request by samdroid-apps**
Replaces #566

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Hum, this is 2 completely different fixes.  I will resubmit!

**Comment by i5o** [comment]
About the display an alert after duplicating bundles... commit, if you let me I would like to finish this

https://github.com/sugarlabs/sugar/pull/296 (I forgot..)

but with your clean code

**Comment by i5o** [comment]
I'm doing it, hope it's ok for you, if not let me know

**Comment by samdroid-apps** [comment]
Yeah sounds good

**Pull request closed without merging**
