### PR TITLE
Fix incomplete port to python3

### PR DESCRIPTION
**Pull request by chimosky**
Call xdg-user-dirs-update to update xdg directories before looking for any user directory.

@kshitijdshah99 kindly test and review, you can test with Pippy activity, you'll need to build sugar
with this branch to test.

Before this change `ActivityToolbarButton -> Create a Sugar activity Bundle` threw an error, this fixes that.

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.

**Comment by chimosky** [comment]
> Reviewed.

Thank you!

**Comment by kshitijdshah99** [comment]
To confirm that I have perfectly understood this issue
1. Firstly I have to build live Sugar
2. Modify the files which you have changed
3. and then test it
Have I addressed the issue correctly?

**Comment by chimosky** [comment]
> To confirm that I have perfectly understood this issue
> 
>     1. Firstly I have to build live Sugar
> 
>     2. Modify the files which you have changed
> 
>     3. and then test it
>        Have I addressed the issue correctly?

The first step is correct, you don't have to modify the files which I've changed, you can just pull my changes, and build sugar with my changes, then restart Sugar.

[L38-L44](https://github.com/sugarlabs/sugar-live-build/blob/master/src/config/hooks/normal/0900-sugar.hook.chroot#L38) shows you how to build Sugar, you'll have to move the files to your machine directories that exist and is part of `sys.path`.

**Comment by kshitijdshah99** [comment]
Ok I think now I get the point, I'll try with this and let you know if any issues👍

**Pull request merged**
