### PR TITLE
Fixed problem of commit 5c3de75 in 32 bits

### PR DESCRIPTION
**Pull request by 163gal**
Fixed problem of commit 5c3de75 in 32 bits

* Now the icon placing will work on 32 bits computers.

### CODE REVIEW

**Comment by i5o** [comment]
Can you elaborate a bit more the commit message?
@quozl can you test this please? Thanks

**Comment by quozl** [comment]
Unknown repository, could not pull or cherry-pick. Workaround:

```
wget https://github.com/sugarlabs/sugar/commit/3f5494113410957923e0d311f369047cbd354558.patch
git am 3f*
```

Tested on XO-4, worked fine.

Reviewed.

**Comment by samdroid-apps** [comment]
Please mention the commit id instead of github number (as @quozl said)

Please mention the fact that this fixes it on 32 bit computers (and any further explanation) in the commit description, not just in the github description.

**Comment by 163gal** [comment]
Done.

**Comment by 163gal** [comment]
Eh... I think I messed up with something, I can't change my commit message. Sorry.

**Comment by quozl** [comment]
@163gal, you should be able to change the commit message.  Check out your branch, and without making any file changes do a
```
git commit --amend
```
Then do a force push.

If you cannot, as a last resort, we can do the commit for you with --author.  We try not to do that because we might not get it to look exactly as you wanted.

I don't like your proposed title change for the pull request.  The first line of the commit message should describe the change in summary; like "Neighborhood icons placement on 32-bits", and the remainder of the description should refer to the commit hash (id) where the regression was introduced.  Look at other first lines of commit messages by others to see the style the project uses.

**Comment by quozl** [comment]
Superceded by #643, closing.

**Pull request closed without merging**
